apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graceful-shutdown-requests
  namespace: graceful-shutdown
spec:
  replicas: 1
  # Update pods with rolling update
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graceful-shutdown-requests
    spec:
      containers:
      - name: requests
        imagePullPolicy: Always
        image: quay.io/tenjin/graceful-shutdown:latest
        command: ["npm", "run", "requests"]