apiVersion: v1
kind: Service
metadata:
  labels:
    app: graceful-shutdown
  name: graceful-shutdown
  namespace: graceful-shutdown
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: graceful-shutdown
  sessionAffinity: None
  type: NodePort
